version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=./db/app.db
      - NODE_ENV=development
      - DATABASE_CLIENT=sqlite
      - CLIENT_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/usr/src/app
    entrypoint: ["sh", "-c", "npm run knex -- migrate:latest && npm run dev"]
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3333
      - MODE=development
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
