version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=/usr/src/app/db/app.db
      - NODE_ENV=production  
      - DATABASE_CLIENT=sqlite
      - CLIENT_ORIGIN=http://localhost:4173
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    environment:
      - VITE_API_URL=http://localhost:3333 
      - MODE=production  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
