version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=/usr/src/app/db/app.db
      - NODE_ENV=production  
      - DATABASE_CLIENT=sqlite
      - CLIENT_ORIGIN=http://localhost:4173
    volumes:
      - ./backend:/usr/src/app
    entrypoint: ["sh", "-c", "npm run knex -- migrate:latest && npm run build && node dist/server.js"]  
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"  
    environment:
      - VITE_API_URL=http://localhost:3333 
      - MODE=production  
    volumes:
      - ./frontend:/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
